[package]
name = "tatacoa-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde.workspace = true
tauri = { version = "2", features = [] }
tatacoa-app-api = { path = "../tatacoa-app-api" }
tatacoa-core = { path = "../tatacoa-core" }

[lints]
workspace = true
