[package]
name = "tatacoa-verifier"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tatacoa-core = { path = "../tatacoa-core" }

[lints]
workspace = true

[[bin]]
name = "tatacoa-verify"
path = "src/main.rs"
