[package]
name = "tatacoa-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
rpassword.workspace = true
tatacoa-core = { path = "../tatacoa-core" }
tatacoa-verifier = { path = "../tatacoa-verifier" }

[lints]
workspace = true

[[bin]]
name = "tatacoa"
path = "src/main.rs"
